// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDO4NJdYG1w7qe6vTOsvMeB9VxQCAdkGg',
    appId: '1:620538503993:web:ac079451ba85fa2efb3ee8',
    messagingSenderId: '620538503993',
    projectId: 'flutter-with--maps',
    authDomain: 'flutter-with--maps.firebaseapp.com',
    storageBucket: 'flutter-with--maps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3I6m0CNLW71K8uzawKaf4d7JbmEQHA4',
    appId: '1:620538503993:android:df72a7e32850e7f1fb3ee8',
    messagingSenderId: '620538503993',
    projectId: 'flutter-with--maps',
    storageBucket: 'flutter-with--maps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZcfU-GJD2lcS0kz-db6YZ_1di2o7Ars',
    appId: '1:620538503993:ios:dc72402452427f73fb3ee8',
    messagingSenderId: '620538503993',
    projectId: 'flutter-with--maps',
    storageBucket: 'flutter-with--maps.appspot.com',
    iosClientId: '620538503993-niuer5e0vumoqi2d7snslheaqstbuoc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGooglemapsBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZcfU-GJD2lcS0kz-db6YZ_1di2o7Ars',
    appId: '1:620538503993:ios:dc72402452427f73fb3ee8',
    messagingSenderId: '620538503993',
    projectId: 'flutter-with--maps',
    storageBucket: 'flutter-with--maps.appspot.com',
    iosClientId: '620538503993-niuer5e0vumoqi2d7snslheaqstbuoc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGooglemapsBloc',
  );
}
